auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_listen_address: 0.0.0.0

common:
  path_prefix: /var/lib/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13 # This is critical for v3.x
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/boltdb-shipper-active
    cache_location: /var/lib/loki/boltdb-shipper-cache
    cache_ttl: 24h
    resync_interval: 5m

  filesystem:
    directory: /var/lib/loki/chunks

limits_config:
  max_query_lookback: 7d
  allow_structured_metadata: false # <--- This line is crucial for boltdb-shipper in v3.x

compactor:
  working_directory: /var/lib/loki/compactor
